[pytest]
python_files = test_*.py #Ejecuta todos los archivos
python_classes = Test* #Ejecuta las clases
python_functions = test_* #Ejecuta las funciones 
addopts = -v --html=reportes.html --self-contained-html
